### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by amitmerchant1990** [elizabethwillard/elizabethwillard.github.io#1]
Hi @elizabethwillard 

Author of [Reverie](https://github.com/amitmerchant1990/reverie) here.

I checked out your site that uses Reverie as a base. I would suggest you update two minor things in order to make the header look much better.

At the moment, because of your long tagline, the navbar links sort of fall off to the next line. To fix this, you can increase the `max-width` of the container in `assets/style.scss`. Here's what I would suggest.

```css
.container {
    margin: 0 auto;
    max-width: 934px;
    padding: 0 10px;
    width: 100%;
}
```

(The best thing would be to shorten the tagline a little bit.)

Next, you can update your avatar to be used as a square aspect ratio since an image of this aspect ratio would look out of place on smaller viewports.

Alternatively, you can update the following styling.

```css
.site-avatar img {
    border-radius: 5px;
    width: 70px;
    height: 70px;
    object-fit: cover;
}
```

Here's what the update would look like.

![image](https://github.com/elizabethwillard/elizabethwillard.github.io/assets/3647841/631825d5-5d31-4f81-a822-9f9726c76cb8)
